# Generated by Django 4.2.7 on 2023-11-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='LessonMaterials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_text', models.TextField()),
                ('image1', models.ImageField(upload_to='lesson_materials')),
                ('image2', models.ImageField(upload_to='lesson_materials')),
                ('image3', models.ImageField(upload_to='lesson_materials')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.lessons')),
            ],
        ),
    ]
