# Generated by Django 5.0 on 2024-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_title', models.CharField(max_length=100)),
                ('chapter_answered', models.IntegerField()),
                ('chapter_total', models.IntegerField()),
                ('chapter_status', models.CharField(max_length=100)),
            ],
        ),
    ]
