# Generated by Django 4.2.7 on 2023-11-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingTypeGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='matching_game')),
                ('image2', models.ImageField(upload_to='matching_game')),
                ('image3', models.ImageField(upload_to='matching_game')),
                ('correct_img1', models.ImageField(upload_to='matching_game')),
                ('correct_img2', models.ImageField(upload_to='matching_game')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapters.lessons')),
            ],
        ),
    ]
